# Project information
site_name: "N04h Today I learned"
site_description: "N04h Today I learned"
site_author: "N04h"
site_url: "https://til.n04h.jp/"

google_analytics: ["UA-163951079-1", "til.n04h.jp"]

# Repository
repo_name: "setsunaMC/til"
repo_url: "https://github.com/setsunaMC/til"

# Copyright
copyright: "Copyright &copy; N04h"

# Documentation and theme
docs_dir: "til"
theme:
  name: null
  custom_dir: "material"
  language: "ja"

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png
  features:
    - tabs

# Navigation
nav:
  - "Home": "index.md"
  - "Ruby":
      - "Rubyの基礎": "ruby/basic.md"
      - "Gemについて": "ruby/gem.md"
      - "Rspecの基本": "ruby/rspec_basic.md"
      - "Rspecのマッチャーについて": "ruby/rspec_matcher.md"
  - "Docker":
      - "Dockerについて": "docker/basic.md"

# Options
extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/setsunaMC"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/Noah_stn"
  font:
    text: "Noto Sans JP"
    code: "Consolas"

extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - fontawesome_markdown
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - codehilite:
      linenums: true
      use_pygments: true
