# Project information
site_name: "N04h til"
site_description: "N04h Today I learned"
site_author: "N04h"
site_url: "https://til.n04h.jp/"

# Repository
repo_name: "Sateright/docs.sateright.com"
repo_url: "https://github.com/Sateright/docs.sateright.com"

# Copyright
copyright: "Copyright &copy; N04h"

# Documentation and theme
docs_dir: "til"
theme:
  name: "material"
  language: "ja"

# Navigation
nav:
  - Home: index.md

# Options
extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/setsunaMC"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/Noah_stn"
  font:
    text: "Noto Sans JP"
    code: "Consolas"

extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - fontawesome_markdown
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - codehilite:
      linenums: true
